Add "getIdToken" user method
bitspittle/firebase-kotlin-bindings pull request #2
Opened 2023-03-04 11:38 UTC by wooodenleg

Add method for retrieving ID token used for server side authentication

2023-03-04 16:33 UTC, bitspittle requested changes
Thank you so much for the PR!

Some comments here, that should be trivial to resolve.

BTW, if my comments are ever long, it's not because I'm pushing back forcefully -- I just want to make sure my thoughts are clear so that you could push back on the push back if you wanted to.

Grateful for the contribution!

2023-03-04 16:33 UTC, bitspittle commented on src/jsMain/kotlin/dev/bitspittle/firebase/externals/auth/Externals.kt
> +    // https://firebase.google.com/docs/reference/js/v8/firebase.User#getidtoken
Nit: Let's link to the auth version of the docs, for consistency with the rest of the file

https://firebase.google.com/docs/reference/js/auth.user#usergetidtoken

2023-03-04 16:33 UTC, bitspittle commented on src/jsMain/kotlin/dev/bitspittle/firebase/auth/Bindings.kt
> +    suspend fun getIdToken(forceRefresh: Boolean? = null) = wrapped.getIdToken(forceRefresh).await()
Nit: Would you mind alphabetizing this method within this class?

It's not a big deal, really -- I just tend to either order methods intentionally (if there's a clear grouping) or, without that, alphabetize them.

The reason is, as a general strategy, it reduces the chance of merge conflicts if a project ever grows to the point of multiple people working on it. (If everyone just adds fields / methods to the end, then merges will inevitably start stomping on each other)

2023-03-04 20:13 UTC, wooodenleg commented on src/jsMain/kotlin/dev/bitspittle/firebase/auth/Bindings.kt
> +    suspend fun getIdToken(forceRefresh: Boolean? = null) = wrapped.getIdToken(forceRefresh).await()
Fair enough 👍

2023-03-04 20:13 UTC, wooodenleg commented on src/jsMain/kotlin/dev/bitspittle/firebase/auth/Bindings.kt
> +    suspend fun getIdToken(forceRefresh: Boolean? = null) = wrapped.getIdToken(forceRefresh).await()
Fair enough 👍

2023-03-04 20:15 UTC, wooodenleg commented
> BTW, if my comments are ever long, it's not because I'm pushing back forcefully -- I just want to make sure my thoughts are clear so that you could push back on the push back if you wanted to.

I don't mind :D I am really pedantic in my code reviews as well so I actually like when someone takes time to give proper criticism

2023-03-05 01:27 UTC, bitspittle approved these changes
Thanks again!

2023-03-05 01:27 UTC, merged